# Generated by Django 5.2.16 on 2026-07-21 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('full', 'Full Business Analysis'), ('revenue', 'Revenue Analysis'), ('products', 'Product Performance'), ('customers', 'Customer Insights'), ('recommendations', 'Business Recommendations')], default='full', max_length=20)),
                ('period', models.CharField(default='30d', help_text='e.g. 7d, 30d, 90d, all', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('data_summary', models.JSONField(blank=True, default=dict)),
                ('insights', models.JSONField(blank=True, default=dict, help_text='Structured insights returned by OpenAI')),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('model_used', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Insight Report',
                'verbose_name_plural': 'AI Insight Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
