# Generated by Django 5.2.16 on 2026-07-21 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/sales/')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0, help_text='Processing time in seconds')),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of validation errors: [{row, column, error}, ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Upload',
                'verbose_name_plural': 'Sales Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('product_name', models.CharField(help_text='Original product name from CSV', max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(help_text='Original customer name from CSV', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, help_text='(selling_price - cost_price) * quantity', max_digits=14)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, help_text='Profit margin percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='customers.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='products.product')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sales.salesupload')),
            ],
            options={
                'verbose_name': 'Sales Record',
                'verbose_name_plural': 'Sales Records',
                'ordering': ['-sale_date', '-created_at'],
                'indexes': [models.Index(fields=['-sale_date'], name='sales_sales_sale_da_37230a_idx'), models.Index(fields=['product', 'sale_date'], name='sales_sales_product_dd838f_idx'), models.Index(fields=['customer', 'sale_date'], name='sales_sales_custome_8e5186_idx')],
            },
        ),
    ]
